# Config file for automatic testing at travis-ci.org
language: python
sudo: required
dist: trusty
python:
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install pdftk -y
install: make install.travis
script: make test.travis
addons:
  postgresql: "9.4"
env:
  - TEST_DATABASE_URL="postgresql+psycopg2://postgres@localhost/test_typeseam"
before_script:
  - psql -c 'create database test_typeseam;' -U postgres
after_success:
  - coveralls
notifications:
    slack: cfa:CYBv6gMC0oGtY1wwI6ZTfldS
